const classes = [
  { value: "ACCT", option: "Accounting" },
  { value: "ASL", option: "American Sign Language" },
  { value: "ANTH", option: "Anthropology" },
  { value: "ART", option: "Art" },
  { value: "BIOL", option: "Biological Science" },
  { value: "BUSM", option: "Business Mgt" },
  { value: "CRDEV", option: "Career Development" },
  { value: "CHEM", option: "Chemistry" },
  { value: "CHIN", option: "Chinese" },
  { value: "COMM", option: "Communication Studies" },
  { value: "CIS", option: "Computer & Information Sciences" },
  { value: "CS", option: "Computer Science" },
  { value: "CRMJ", option: "Criminal Justice" },
  { value: "ECON", option: "Economics" },
  { value: "EDU", option: "Education" },
  { value: "ELED", option: "Elementary Education" },
  { value: "EMGT", option: "Emergency Management" },
  { value: "ENGL", option: "English" },
  { value: "EIL", option: "English as Int'l Language" },
  { value: "ENTR", option: "Entrepreneurship" },
  { value: "EXS", option: "Exercise Sport Science" },
  { value: "FILM", option: "Film" },
  { value: "FIN", option: "Finance" },
  { value: "FORS", option: "Forensic Science" },
  { value: "FREN", option: "French" },
  { value: "GEOG", option: "Geography" },
  { value: "HAWN", option: "Hawaiian" },
  { value: "HWST", option: "Hawaiian Studies" },
  { value: "HLTH", option: "Health" },
  { value: "HIST", option: "History" },
  { value: "HEC", option: "Home Economics" },
  { value: "HTM", option: "Hospitality Tourism Mgt" },
  { value: "HUM", option: "Humanities" },
  { value: "IS", option: "Information System" },
  { value: "IT", option: "Information Technology" },
  { value: "ICS", option: "International Cultural Studies" },
  { value: "IPB", option: "Intercultural Peacebuilding" },
  { value: "JPN", option: "Japanese" },
  { value: "LING", option: "Linguistics" },
  { value: "AMOR", option: "Maori" },
  { value: "MATH", option: "Mathematics" },
  { value: "MUSC", option: "Music" },
  { value: "OCEN", option: "Oceanography" },
  { value: "PAIS", option: "Pacific Island Studies" },
  { value: "PHSC", option: "Physical Science" },
  { value: "POSC", option: "Political Science" },
  { value: "PSYC", option: "Psychology" },
  { value: "PMGT", option: "Public Management" },
  { value: "REL", option: "Religion" },
  { value: "SCI", option: "Science" },
  { value: "SAMN", option: "Samoan" },
  { value: "SCED", option: "Secondary Education" },
  { value: "SOCW", option: "Social Work" },
  { value: "SPAN", option: "Spanish" },
  { value: "SPED", option: "Special Education" },
  { value: "STDEV", option: "Student Development" },
  { value: "TESOL", option: "TESOL" },
  { value: "THEA", option: "Theatre" },
  { value: "TONG", option: "Tongan" },
  { value: "WLNG", option: "World Language" },
];
